cursor #e2e3d9
cursor_text_color #c4c8ba

foreground            #e2e3d9
background            #1e2319
selection_foreground  #29341f
selection_background  #bfcbae
url_color             #afd18c

# black
color8   #373a33
color0   #11140e

# red
color9 #ffb595
color1 #ffb595

# green
color10 #aad291
color2 #aad291

# yellow
color11 #bdce80
color3 #bdce80

# blue
# color4  #afc6ff
color12 #afc6ff
color4  #afd18c

# magenta
color13 #fcb0d5
color5 #fcb0d5

# cyan
color14 #84d5c4
color6 #84d5c4

# white
color7 #e2e3d9
color15 #c4c8ba
