
font_size 13.0

background_opacity 0.75

# Cursor
cursor_shape beam
cursor_trail 1

# Padding (why weird value? consistency with foot)
window_margin_width 1.75

# No stupid close confirmation
confirm_os_window_close 0



# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

tab_bar_style                   custom
tab_separator                   ""
# REF: https://github.com/kovidgoyal/kitty/discussions/4447
tab_fade                        0 0 0 0
tab_title_template              "{fmt.fg._415c6d}{fmt.bg.default}  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "{fmt.fg._83b6af}{fmt.bg.default}  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
tab_bar_edge                    top
tab_bar_align                   left
tab_bar_margin_width            0.0
tab_bar_margin_height           10.0 0.0
active_tab_font_style           bold-italic
inactive_tab_font_style         normal
tab_bar_min_tabs                2
tab_activity_symbol             none
bell_on_tab                     no


include themes/matugen.conf
allow_remote_control yes
