[config]
reload_apps = true

[config.reload_apps_list]
kitty = true
gtk_theme = true

[config.wallpaper]
command = "swww"
arguments = [ "img", "-t", "outer", "--transition-duration", "1.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/rofi-colors.rasi'

#[templates.kitty]
#input_path = '~/.config/matugen/templates/kitty-colors.conf'
#output_path = '~/.config/kitty/colors.conf'
#post_hook = "killall -SIGUSR1 kitty && kitty @ set-colors -a -c ~/.config/kitty/colors.conf"

#[templates.kitty_tab_bar_colors]
#input_path = "~/.config/matugen/templates/kitty_tab_bar_colors.py.template"
#output_path = "~/.config/kitty/tab_bar_colors.py"
#post_hook = "kitty @ set-colors -a -c ~/.config/kitty/colors.conf"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/matugen"
post_hook = "ydotool key 29:1 42:1 51:1 51:0 42:0 29:0"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.ghostty-gtk4]
input_path = '~/.config/matugen/templates/gtk4-colors.css'
output_path = '~/.config/ghostty/themes/theme.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen-colors.conf'
post_hook = 'hyprctl reload'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFEB3B"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
