cursor #e4e2e1
cursor_text_color #c3c7c8

foreground            #e4e2e1
background            #131313
selection_foreground  #2d3132
selection_background  #c3c7c8
url_color             #bcc9cb

# black
color8   #c3c7c8
color0   #131313

# red
color1   #ffb4ab
color9   #ffb4ab

# green
color2   #b2a7bb
color10  #cbc4d1

# yellow
color3   #b8d0d4
color11  #d8e5e7

# blue
color4  #9fb2b5
color12 #ffb4ab

# magenta
color5   #b2a7bb
color13  #cbc4d1

# cyan
color6   #b8d0d4
color14  #d8e5e7

# white
color15  #e4e2e1
color7  #a8aeb0
