misc {
    disable_hyprland_logo = 1
    disable_splash_rendering = 1
    focus_on_activate = 1
    allow_session_lock_restore = true
    middle_click_paste = false
}

listener {
    # timeout = 300 # 5 minutes
    # on-timeout = loginctl lock-session # lock screen
}

listener {
    # timeout = 330 # 5.5 minutes
    # on-timeout = hyprctl dispatch dpms off # turn off screen
    # on-resume = hyprctl dispatch dpms on # turn on screen
}
