//
// Telegram Desktop Theme - Generated by matugen
// This template maps Material You color roles to Telegram UI elements.
//

// Window
windowBg: {{ colors.background.default.hex }};
windowBgOver: {{ colors.surface_container.default.hex }};
windowBgActive: {{ colors.surface_container_high.default.hex }};
windowFg: {{ colors.on_surface.default.hex }};
windowFgOver: {{ colors.on_surface_variant.default.hex }};

// Title bar
titleBg: {{ colors.surface_container_highest.default.hex }};
titleFg: {{ colors.on_surface.default.hex }};

// Main text
historyTextFg: {{ colors.on_surface.default.hex }};
historyTextFgOver: {{ colors.on_surface_variant.default.hex }};
historyUnreadBarFg: {{ colors.primary.default.hex }};
historyFileThumbFg: {{ colors.on_surface.default.hex }};

// Links
linksFg: {{ colors.primary.default.hex }};
linksFgOver: {{ colors.tertiary.default.hex }};

// Messages & Bubbles
msgInBg: {{ colors.surface_container.default.hex }};
msgInBgSelected: {{ colors.surface_container_high.default.hex }};
msgOutBg: {{ colors.primary_container.default.hex }};
msgOutBgSelected: {{ colors.secondary_container.default.hex }};
msgSelectBg: {{ colors.secondary_container.default.hex }};
msgStickerBg: #00000000;

// Message text colors
msgInFg: {{ colors.on_surface.default.hex }};
msgOutFg: {{ colors.on_primary_container.default.hex }};
msgServiceFg: {{ colors.primary.default.hex }};
msgDateFg: {{ colors.on_surface_variant.default.hex }};

// Mentions
mentionFg: {{ colors.on_secondary_container.default.hex }};
mentionBg: {{ colors.secondary_container.default.hex }};
mentionFgOver: {{ colors.on_secondary_container.default.hex }};
mentionBgOver: {{ colors.secondary.default.hex }};


// Buttons & Controls
buttonBg: {{ colors.primary.default.hex }};
buttonBgOver: {{ colors.secondary.default.hex }};
buttonFg: {{ colors.on_primary.default.hex }};
botKbBg: {{ colors.surface_container_high.default.hex }};
botKbFg: {{ colors.on_surface_variant.default.hex }};

// Input Fields
fieldBg: {{ colors.surface_container_high.default.hex }};
fieldBgActive: {{ colors.surface_container_highest.default.hex }};
fieldFg: {{ colors.on_surface.default.hex }};
fieldBorderFg: {{ colors.outline.default.hex }};

// Scrollbars
scrollBarBg: {{ colors.surface_container_high.default.hex }};
scrollBarBgOver: {{ colors.surface_container_highest.default.hex }};
scrollBg: {{ colors.outline.default.hex }};
scrollBgOver: {{ colors.primary.default.hex }};

// Pinned Message bar
pinnedBg: {{ colors.surface_container_high.default.hex }};

// Pre-formatted text / code blocks
preformattedBg: {{ colors.surface_container_low.default.hex }};
preformattedFg: {{ colors.on_surface.default.hex }};

// Generic "active" or "accent" color
activeButtonFg: {{ colors.on_primary.default.hex }};
activeLineFg: {{ colors.primary.default.hex }};
activeLineFgError: {{ colors.error.default.hex }};

// Left Column (Dialogs list)
dialogsBg: {{ colors.surface.default.hex }};
dialogsNameFg: {{ colors.on_surface.default.hex }};
dialogsTextFg: {{ colors.on_surface_variant.default.hex }};
dialogsDateFg: {{ colors.on_surface_variant.default.hex }};
dialogsUnreadFg: {{ colors.on_primary.default.hex }};
dialogsUnreadBg: {{ colors.primary.default.hex }};
dialogsUnreadBgMuted: {{ colors.secondary.default.hex }};

dialogsBgOver: {{ colors.surface_container.default.hex }};
dialogsBgActive: {{ colors.surface_container_high.default.hex }};

// Others
sideBarBg: {{ colors.surface_container_low.default.hex }};
sideBarFg: {{ colors.on_surface.default.hex }};
callArrowFg: {{ colors.tertiary.default.hex }};
